#!/bin/bash
# Human-friendly project name.
PROJECT="Trashman"
# Computer-friendly project name, [a-z0-9_\-]
PROJECTLC="trashman"

# Git repository name.  Using $PROJECTLC is recommended.
GITREPO=$PROJECTLC

# Locale type.  One of:
# none      Do not generate nor use any locales.
# gettext   Use GNU gettext (gettext module).
# pyqt4     Use the Qt locale tools (stock Qt + PyQt4).
# pyside    Use the Qt locale tools (stock Qt + PySide).
LOCALETYPE="gettext"

# Python versions supported.
PYTHON2=1
PYTHON3=1

# AUR package names.  You still need to change PKGBUILDs!
AUR_PKGNAME=$PROJECTLC
AUR_PKGNAME_GIT=$PROJECTLC"-git"

# Whether or not to create AUR -git packages. (true/false)
AUR_GIT_PACKAGE="true"
