name: Trashman CI
on: [push, pull_request]

jobs:
  tests:
    name: Tests on Python ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9, pypy-3.7]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Upgrade packaging stack
        run: |
          python -m pip install --upgrade-strategy eager -U pip setuptools wheel
      - name: Install Trashman
        run: |
          python -m pip install .
      - name: Run tests
        run: |
          python tests.py
